[versions]
gradle-node = "7.1.0"
kotlin = "2.4.10"
mockk = "1.14.11"
spotless = "8.9.0"
spring-boot = "4.1.0"
version-catalog-update = "1.1.0"

openapi-generator = "7.11.0"

[libraries]
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
jakarta-validation-api = { module = "jakarta.validation:jakarta.validation-api", version = "3.1.1" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
swagger-annotations = { module = "io.swagger.core.v3:swagger-annotations", version = "2.2.28" }

[plugins]
gradle-node = { id = "com.github.node-gradle.node", version.ref = "gradle-node" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
